### ISSUE TITLE
BBCode Admin Improvements

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#2403]
Currently BBCodes need to move up and down by link. Implement Drag/Drop to Sort Order while mantaining links functionality in a ellipsis dropdown.

- [ ] Implement Jquery UI Drag/Drop
- [ ] Implement Better Text Previews
- [ ] Implement Better UI Arrangements
- [ ] Implement BBcode PHP Functions SDK (Optimization for PHP 8+)
- [ ] Implement Better Admin Interface
