### ISSUE TITLE
New get_icon() function

### ISSUE THREAD

**Issue by meangczac** [PHPFusion/PHPFusion#2405]
With the good amount of icons being made available everyday, it is tough to keep everything up to date. And since implementations of each library is depending on personal taste or preferences, files are being edited all over to change to these icons. 

In PHPFusion, we have commonly used icons such as caret, angle, ellipsis, search, filter, etc. 

Hence, a new get_icon() function to replace this is very much feasible.

For example of this implementation is:

```echo get_icon('search').' '.$locale['search']```

The get_icon() can be 'fad fa-search', 'fa fa-search' 'lnr-search', 'bx bx-search' depending on what the final user requires. 

The implementation will be as follows:

- [x] ImageRepo to add 2 additional function - setIcon and getIcon.
- [ ] Under Each Font Icon Library, we add a new php file with a predefined array key to values.
- [ ] Under Each Theme, we can also add a predefined array of icons.
- [ ] Add get_icon function to be able to be used in Twig templates.

If the theme has a rule defined, that will be the displayed icon. Otherwise, the system rule will be used. 

For user, they only have choices to use which "Set of icons" 
Font Awesome 4, Font Awesome 5, Font Awesome 6, Linearcons, Entypo, MoonIco etc etc. 

For now it will be good enough.

**Comment by meangczac** [comment]
https://github.com/PHPFusion/docs/commit/7de72fcdb987a95ee7f8dcbda0014e86c371503d
